config/routes.rb
Rails.application.routes.draw do

  post 'trucks/:id/reEngine', to: 'trucks#reEngine', as: 'truck_reEngine'
  post 'trucks/:id/reTransmission', to: 'trucks#reTransmission', as: 'truck_reTransmission'
  post 'trucks/:id/reGear', to: 'trucks#reGear', as: 'truck_reGear'
  post 'trucks/:id/reAir', to: 'trucks#reAir', as: 'truck_reAir'
  post 'trucks/:id/reCoolant', to: 'trucks#reCoolant', as: 'truck_reCoolant'
  post 'trucks/:id/reBlower', to: 'trucks#reBlower', as: 'truck_reBlower'

  resources :maintenances
  devise_for :users
  resources :blowers
  resources :coolants
  resources :airs
  resources :gears
  resources :transmissions
  resources :engines
  resources :trips

  resources :trucks do
    resources :trips
  end

  root to: "trucks#index"

end

app/models/blower.rb
# == Schema Information
#
# Table name: blowers
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  truck_id   :integer
#

class Blower < ActiveRecord::Base
  has_many :trips
end

app/controllers/blowers_controller.rb
class BlowersController < ApplicationController
  load_and_authorize_resource
  before_action :set_blower, only: [:show, :edit, :update, :destroy]

  # GET /blowers
  # GET /blowers.json
  def index
    @blowers = Blower.all
  end

  # GET /blowers/1
  # GET /blowers/1.json
  def show
  end

  # GET /blowers/new
  def new
    @blower = Blower.new
  end

  # GET /blowers/1/edit
  def edit
  end

  # POST /blowers
  # POST /blowers.json
  def create
    @blower = Blower.new(blower_params)

    respond_to do |format|
      if @blower.save
        format.html { redirect_to @blower, notice: 'Blower was successfully created.' }
        format.json { render :show, status: :created, location: @blower }
      else
        format.html { render :new }
        format.json { render json: @blower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blowers/1
  # PATCH/PUT /blowers/1.json
  def update
    respond_to do |format|
      if @blower.update(blower_params)
        format.html { redirect_to @blower, notice: 'Blower was successfully updated.' }
        format.json { render :show, status: :ok, location: @blower }
      else
        format.html { render :edit }
        format.json { render json: @blower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blowers/1
  # DELETE /blowers/1.json
  def destroy
    @blower.destroy
    respond_to do |format|
      format.html { redirect_to blowers_url, notice: 'Blower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blower
      @blower = Blower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blower_params
      params.fetch(:blower, {})
    end
end

app/helpers/blowers_helper.rb
module BlowersHelper
end

app/views/blowers/_form.html.erb
<%= form_for(@blower) do |f| %>
  <% if @blower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blower.errors.count, "error") %> prohibited this blower from being saved:</h2>

      <ul>
      <% @blower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blowers/edit.html.erb
<h1>Editing Blower</h1>

<%= render 'form' %>

<%= link_to 'Show', @blower %> |
<%= link_to 'Back', blowers_path %>

app/views/blowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blowers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blowers.each do |blower| %>
      <tr>
        <td><%= link_to 'Show', blower %></td>
        <td><%= link_to 'Edit', edit_blower_path(blower) %></td>
        <td><%= link_to 'Destroy', blower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blower', new_blower_path %>

app/views/blowers/new.html.erb
<h1>New Blower</h1>

<%= render 'form' %>

<%= link_to 'Back', blowers_path %>

app/views/blowers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blower_path(@blower) %> |
<%= link_to 'Back', blowers_path %>