config/routes.rb
Rails.application.routes.draw do

  post 'trucks/:id/reEngine', to: 'trucks#reEngine', as: 'truck_reEngine'
  post 'trucks/:id/reTransmission', to: 'trucks#reTransmission', as: 'truck_reTransmission'
  post 'trucks/:id/reGear', to: 'trucks#reGear', as: 'truck_reGear'
  post 'trucks/:id/reAir', to: 'trucks#reAir', as: 'truck_reAir'
  post 'trucks/:id/reCoolant', to: 'trucks#reCoolant', as: 'truck_reCoolant'
  post 'trucks/:id/reBlower', to: 'trucks#reBlower', as: 'truck_reBlower'

  resources :maintenances
  devise_for :users
  resources :blowers
  resources :coolants
  resources :airs
  resources :gears
  resources :transmissions
  resources :engines
  resources :trips

  resources :trucks do
    resources :trips
  end

  root to: "trucks#index"

end

app/models/gear.rb
# == Schema Information
#
# Table name: gears
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  truck_id   :integer
#

class Gear < ActiveRecord::Base
  has_many :trips
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  load_and_authorize_resource
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.all
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
  end

  # GET /gears/new
  def new
    @gear = Gear.new
  end

  # GET /gears/1/edit
  def edit
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear
      @gear = Gear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_params
      params.fetch(:gear, {})
    end
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/gears/_form.html.erb
<%= form_for(@gear) do |f| %>
  <% if @gear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gear.errors.count, "error") %> prohibited this gear from being saved:</h2>

      <ul>
      <% @gear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gears/edit.html.erb
<h1>Editing Gear</h1>

<%= render 'form' %>

<%= link_to 'Show', @gear %> |
<%= link_to 'Back', gears_path %>

app/views/gears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gears</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gears.each do |gear| %>
      <tr>
        <td><%= link_to 'Show', gear %></td>
        <td><%= link_to 'Edit', edit_gear_path(gear) %></td>
        <td><%= link_to 'Destroy', gear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gear', new_gear_path %>

app/views/gears/new.html.erb
<h1>New Gear</h1>

<%= render 'form' %>

<%= link_to 'Back', gears_path %>

app/views/gears/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gear_path(@gear) %> |
<%= link_to 'Back', gears_path %>