config/routes.rb
Rails.application.routes.draw do

  post 'trucks/:id/reEngine', to: 'trucks#reEngine', as: 'truck_reEngine'
  post 'trucks/:id/reTransmission', to: 'trucks#reTransmission', as: 'truck_reTransmission'
  post 'trucks/:id/reGear', to: 'trucks#reGear', as: 'truck_reGear'
  post 'trucks/:id/reAir', to: 'trucks#reAir', as: 'truck_reAir'
  post 'trucks/:id/reCoolant', to: 'trucks#reCoolant', as: 'truck_reCoolant'
  post 'trucks/:id/reBlower', to: 'trucks#reBlower', as: 'truck_reBlower'

  resources :maintenances
  devise_for :users
  resources :blowers
  resources :coolants
  resources :airs
  resources :gears
  resources :transmissions
  resources :engines
  resources :trips

  resources :trucks do
    resources :trips
  end

  root to: "trucks#index"

end

app/models/coolant.rb
# == Schema Information
#
# Table name: coolants
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  truck_id   :integer
#

class Coolant < ActiveRecord::Base
  has_many :trips
end

app/controllers/coolants_controller.rb
class CoolantsController < ApplicationController
  load_and_authorize_resource
  before_action :set_coolant, only: [:show, :edit, :update, :destroy]

  # GET /coolants
  # GET /coolants.json
  def index
    @coolants = Coolant.all
  end

  # GET /coolants/1
  # GET /coolants/1.json
  def show
  end

  # GET /coolants/new
  def new
    @coolant = Coolant.new
  end

  # GET /coolants/1/edit
  def edit
  end

  # POST /coolants
  # POST /coolants.json
  def create
    @coolant = Coolant.new(coolant_params)

    respond_to do |format|
      if @coolant.save
        format.html { redirect_to @coolant, notice: 'Coolant was successfully created.' }
        format.json { render :show, status: :created, location: @coolant }
      else
        format.html { render :new }
        format.json { render json: @coolant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coolants/1
  # PATCH/PUT /coolants/1.json
  def update
    respond_to do |format|
      if @coolant.update(coolant_params)
        format.html { redirect_to @coolant, notice: 'Coolant was successfully updated.' }
        format.json { render :show, status: :ok, location: @coolant }
      else
        format.html { render :edit }
        format.json { render json: @coolant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coolants/1
  # DELETE /coolants/1.json
  def destroy
    @coolant.destroy
    respond_to do |format|
      format.html { redirect_to coolants_url, notice: 'Coolant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coolant
      @coolant = Coolant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coolant_params
      params.fetch(:coolant, {})
    end
end

app/helpers/coolants_helper.rb
module CoolantsHelper
end

app/views/coolants/_form.html.erb
<%= form_for(@coolant) do |f| %>
  <% if @coolant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coolant.errors.count, "error") %> prohibited this coolant from being saved:</h2>

      <ul>
      <% @coolant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coolants/edit.html.erb
<h1>Editing Coolant</h1>

<%= render 'form' %>

<%= link_to 'Show', @coolant %> |
<%= link_to 'Back', coolants_path %>

app/views/coolants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coolants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coolants.each do |coolant| %>
      <tr>
        <td><%= link_to 'Show', coolant %></td>
        <td><%= link_to 'Edit', edit_coolant_path(coolant) %></td>
        <td><%= link_to 'Destroy', coolant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coolant', new_coolant_path %>

app/views/coolants/new.html.erb
<h1>New Coolant</h1>

<%= render 'form' %>

<%= link_to 'Back', coolants_path %>

app/views/coolants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_coolant_path(@coolant) %> |
<%= link_to 'Back', coolants_path %>